using System.Linq;

namespace AsmResolver.DotNet.Extensions
{
    /// <summary>
    /// Provides extensions for metadata members that have custom attributes
    /// </summary>
    public static class HasCustomAttributeExtensions
    {
        /// <summary>
        /// Indicates whether the specified member is compiler generated.
        /// </summary>
        /// <param name="attribute">The referenced member to check</param>
        /// <returns><c>true</c> if the member was generated by the compiler, otherwise <c>false</c></returns>
        public static bool IsCompilerGenerated(this IHasCustomAttribute attribute)
        {
            return attribute.CustomAttributes.Any(c =>
                c.Constructor.DeclaringType.IsTypeOf("System.Runtime.CompilerServices", "CompilerGeneratedAttribute"));
        }    
    }
}