//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmResolver.DotNet.Tests.Properties {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AsmResolver.DotNet.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static byte[] HelloWorld {
            get {
                object obj = ResourceManager.GetObject("HelloWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_NetCore {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_NetCore", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_InvalidMethodBody {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_InvalidMethodBody", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_MaliciousNestedClassLoop {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_MaliciousNestedClassLoop", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_MaliciousNestedClassLoop2 {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_MaliciousNestedClassLoop2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_IllegalTypeSpecInTypeDefOrRefSig {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_IllegalTypeSpecInTypeDefOrRefSig", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_MaliciousTypeSpecLoop {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_MaliciousTypeSpecLoop", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_NoUSStream {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_NoUSStream", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_MaliciousExportedTypeLoop {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_MaliciousExportedTypeLoop", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Assembly1_MaliciousExportedTypeLoop {
            get {
                object obj = ResourceManager.GetObject("Assembly1_MaliciousExportedTypeLoop", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Assembly2_MaliciousExportedTypeLoop {
            get {
                object obj = ResourceManager.GetObject("Assembly2_MaliciousExportedTypeLoop", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_Forwarder {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_Forwarder", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_WithAttribute {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_WithAttribute", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_SingleFile_V1 {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_SingleFile_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_SingleFile_V2 {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_SingleFile_V2", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_SingleFile_V6 {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_SingleFile_V6", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_SingleFile_V6_WithResources {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_SingleFile_V6_WithResources", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_UnusualNestedTypeRefOrder {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_UnusualNestedTypeRefOrder", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleBlobStream {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleBlobStream", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleBlobStream_EnC {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleBlobStream_EnC", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleGuidStream {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleGuidStream", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleGuidStream_EnC {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleGuidStream_EnC", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleStringsStream {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleStringsStream", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleStringsStream_EnC {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleStringsStream_EnC", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleUserStringsStream {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleUserStringsStream", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HelloWorld_DoubleUserStringsStream_EnC {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_DoubleUserStringsStream_EnC", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Assembly1_Forwarder {
            get {
                object obj = ResourceManager.GetObject("Assembly1_Forwarder", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Assembly2_Actual {
            get {
                object obj = ResourceManager.GetObject("Assembly2_Actual", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ConstantZeroValueColumn {
            get {
                object obj = ResourceManager.GetObject("ConstantZeroValueColumn", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ActualLibrary {
            get {
                object obj = ResourceManager.GetObject("ActualLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ForwarderLibrary {
            get {
                object obj = ResourceManager.GetObject("ForwarderLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ForwarderRefTest {
            get {
                object obj = ResourceManager.GetObject("ForwarderRefTest", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] TheAnswer_NetFx {
            get {
                object obj = ResourceManager.GetObject("TheAnswer_NetFx", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] HandlerEndAtEndOfMethodBody {
            get {
                object obj = ResourceManager.GetObject("HandlerEndAtEndOfMethodBody", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] FieldRvaTest {
            get {
                object obj = ResourceManager.GetObject("FieldRvaTest", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] DifferentNetVersion_MainApp {
            get {
                object obj = ResourceManager.GetObject("DifferentNetVersion_MainApp", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] DifferentNetVersion_Library {
            get {
                object obj = ResourceManager.GetObject("DifferentNetVersion_Library", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] CallManagedExport_X86 {
            get {
                object obj = ResourceManager.GetObject("CallManagedExport_X86", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] CallManagedExport_X64 {
            get {
                object obj = ResourceManager.GetObject("CallManagedExport_X64", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] MyLibrary_X86 {
            get {
                object obj = ResourceManager.GetObject("MyLibrary_X86", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] MyLibrary_X64 {
            get {
                object obj = ResourceManager.GetObject("MyLibrary_X64", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ModuleCctorAbsentNet6 {
            get {
                object obj = ResourceManager.GetObject("ModuleCctorAbsentNet6", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ModuleCctorLookalikeNet6 {
            get {
                object obj = ResourceManager.GetObject("ModuleCctorLookalikeNet6", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ModuleCctorNet6 {
            get {
                object obj = ResourceManager.GetObject("ModuleCctorNet6", resourceCulture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ModuleCctorNetFramework {
            get {
                object obj = ResourceManager.GetObject("ModuleCctorNetFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
