using System.Linq;

namespace AsmResolver.Net.Cil
{
    public static class CilOpCodes
    {
        public static readonly CilOpCode[] SingleByteOpCodes = new CilOpCode[256];
        public static readonly CilOpCode[] MultiByteOpCodes = new CilOpCode[256];

        public static CilOpCode GetOpCode(CilCode code)
        {
            var value = (int)code;
            if ((value & 0xFE00) == 0xFE00)
                return MultiByteOpCodes[value & 0xFF];
            return SingleByteOpCodes[value & 0xFF];
        }

        public static CilOpCode GetOpCode(string name)
        {
            return SingleByteOpCodes.Concat(MultiByteOpCodes).First(x => x.Name == name);
        }

        // taken from the System.Reflection.Emit.OpCodes class (except for InlineArgument opcodes).
        // ReSharper disable InconsistentNaming

        public static readonly CilOpCode Nop = new CilOpCode(CilCode.Nop, 6556325);
        public static readonly CilOpCode Break = new CilOpCode(CilCode.Break, 6556197);
        public static readonly CilOpCode Ldarg_0 = new CilOpCode(CilCode.Ldarg_0, 275120805);
        public static readonly CilOpCode Ldarg_1 = new CilOpCode(CilCode.Ldarg_1, 275120805);
        public static readonly CilOpCode Ldarg_2 = new CilOpCode(CilCode.Ldarg_2, 275120805);
        public static readonly CilOpCode Ldarg_3 = new CilOpCode(CilCode.Ldarg_3, 275120805);
        public static readonly CilOpCode Ldloc_0 = new CilOpCode(CilCode.Ldloc_0, 275120805);
        public static readonly CilOpCode Ldloc_1 = new CilOpCode(CilCode.Ldloc_1, 275120805);
        public static readonly CilOpCode Ldloc_2 = new CilOpCode(CilCode.Ldloc_2, 275120805);
        public static readonly CilOpCode Ldloc_3 = new CilOpCode(CilCode.Ldloc_3, 275120805);
        public static readonly CilOpCode Stloc_0 = new CilOpCode(CilCode.Stloc_0, -261877083);
        public static readonly CilOpCode Stloc_1 = new CilOpCode(CilCode.Stloc_1, -261877083);
        public static readonly CilOpCode Stloc_2 = new CilOpCode(CilCode.Stloc_2, -261877083);
        public static readonly CilOpCode Stloc_3 = new CilOpCode(CilCode.Stloc_3, -261877083);
        public static readonly CilOpCode Ldarg_S = new CilOpCode(CilCode.Ldarg_S, 275120820);
        public static readonly CilOpCode Ldarga_S = new CilOpCode(CilCode.Ldarga_S, 275382964);
        public static readonly CilOpCode Starg_S = new CilOpCode(CilCode.Starg_S, -261877068);
        public static readonly CilOpCode Ldloc_S = new CilOpCode(CilCode.Ldloc_S, 275120818);
        public static readonly CilOpCode Ldloca_S = new CilOpCode(CilCode.Ldloca_S, 275382962);
        public static readonly CilOpCode Stloc_S = new CilOpCode(CilCode.Stloc_S, -261877070);
        public static readonly CilOpCode Ldnull = new CilOpCode(CilCode.Ldnull, 275909285);
        public static readonly CilOpCode Ldc_I4_M1 = new CilOpCode(CilCode.Ldc_I4_M1, 275382949);
        public static readonly CilOpCode Ldc_I4_0 = new CilOpCode(CilCode.Ldc_I4_0, 275382949);
        public static readonly CilOpCode Ldc_I4_1 = new CilOpCode(CilCode.Ldc_I4_1, 275382949);
        public static readonly CilOpCode Ldc_I4_2 = new CilOpCode(CilCode.Ldc_I4_2, 275382949);
        public static readonly CilOpCode Ldc_I4_3 = new CilOpCode(CilCode.Ldc_I4_3, 275382949);
        public static readonly CilOpCode Ldc_I4_4 = new CilOpCode(CilCode.Ldc_I4_4, 275382949);
        public static readonly CilOpCode Ldc_I4_5 = new CilOpCode(CilCode.Ldc_I4_5, 275382949);
        public static readonly CilOpCode Ldc_I4_6 = new CilOpCode(CilCode.Ldc_I4_6, 275382949);
        public static readonly CilOpCode Ldc_I4_7 = new CilOpCode(CilCode.Ldc_I4_7, 275382949);
        public static readonly CilOpCode Ldc_I4_8 = new CilOpCode(CilCode.Ldc_I4_8, 275382949);
        public static readonly CilOpCode Ldc_I4_S = new CilOpCode(CilCode.Ldc_I4_S, 275382960);
        public static readonly CilOpCode Ldc_I4 = new CilOpCode(CilCode.Ldc_I4, 275384994);
        public static readonly CilOpCode Ldc_I8 = new CilOpCode(CilCode.Ldc_I8, 275516067);
        public static readonly CilOpCode Ldc_R4 = new CilOpCode(CilCode.Ldc_R4, 275647153);
        public static readonly CilOpCode Ldc_R8 = new CilOpCode(CilCode.Ldc_R8, 275778215);
        public static readonly CilOpCode Dup = new CilOpCode(CilCode.Dup, 275258021);
        public static readonly CilOpCode Pop = new CilOpCode(CilCode.Pop, -261875035);
        public static readonly CilOpCode Jmp = new CilOpCode(CilCode.Jmp, 23333444);
        public static readonly CilOpCode Call = new CilOpCode(CilCode.Call, 7842372);
        public static readonly CilOpCode Calli = new CilOpCode(CilCode.Calli, 7842377);
        public static readonly CilOpCode Ret = new CilOpCode(CilCode.Ret, 23440101);
        public static readonly CilOpCode Br_S = new CilOpCode(CilCode.Br_S, 23331343);
        public static readonly CilOpCode Brfalse_S = new CilOpCode(CilCode.Brfalse_S, -261868945);
        public static readonly CilOpCode Brtrue_S = new CilOpCode(CilCode.Brtrue_S, -261868945);
        public static readonly CilOpCode Beq_S = new CilOpCode(CilCode.Beq_S, -530308497);
        public static readonly CilOpCode Bge_S = new CilOpCode(CilCode.Bge_S, -530308497);
        public static readonly CilOpCode Bgt_S = new CilOpCode(CilCode.Bgt_S, -530308497);
        public static readonly CilOpCode Ble_S = new CilOpCode(CilCode.Ble_S, -530308497);
        public static readonly CilOpCode Blt_S = new CilOpCode(CilCode.Blt_S, -530308497);
        public static readonly CilOpCode Bne_Un_S = new CilOpCode(CilCode.Bne_Un_S, -530308497);
        public static readonly CilOpCode Bge_Un_S = new CilOpCode(CilCode.Bge_Un_S, -530308497);
        public static readonly CilOpCode Bgt_Un_S = new CilOpCode(CilCode.Bgt_Un_S, -530308497);
        public static readonly CilOpCode Ble_Un_S = new CilOpCode(CilCode.Ble_Un_S, -530308497);
        public static readonly CilOpCode Blt_Un_S = new CilOpCode(CilCode.Blt_Un_S, -530308497);
        public static readonly CilOpCode Br = new CilOpCode(CilCode.Br, 23333376);
        public static readonly CilOpCode Brfalse = new CilOpCode(CilCode.Brfalse, -261866912);
        public static readonly CilOpCode Brtrue = new CilOpCode(CilCode.Brtrue, -261866912);
        public static readonly CilOpCode Beq = new CilOpCode(CilCode.Beq, -530308512);
        public static readonly CilOpCode Bge = new CilOpCode(CilCode.Bge, -530308512);
        public static readonly CilOpCode Bgt = new CilOpCode(CilCode.Bgt, -530308512);
        public static readonly CilOpCode Ble = new CilOpCode(CilCode.Ble, -530308512);
        public static readonly CilOpCode Blt = new CilOpCode(CilCode.Blt, -530308512);
        public static readonly CilOpCode Bne_Un = new CilOpCode(CilCode.Bne_Un, -530308512);
        public static readonly CilOpCode Bge_Un = new CilOpCode(CilCode.Bge_Un, -530308512);
        public static readonly CilOpCode Bgt_Un = new CilOpCode(CilCode.Bgt_Un, -530308512);
        public static readonly CilOpCode Ble_Un = new CilOpCode(CilCode.Ble_Un, -530308512);
        public static readonly CilOpCode Blt_Un = new CilOpCode(CilCode.Blt_Un, -530308512);
        public static readonly CilOpCode Switch = new CilOpCode(CilCode.Switch, -261866901);
        public static readonly CilOpCode Ldind_I1 = new CilOpCode(CilCode.Ldind_I1, 6961829);
        public static readonly CilOpCode Ldind_U1 = new CilOpCode(CilCode.Ldind_U1, 6961829);
        public static readonly CilOpCode Ldind_I2 = new CilOpCode(CilCode.Ldind_I2, 6961829);
        public static readonly CilOpCode Ldind_U2 = new CilOpCode(CilCode.Ldind_U2, 6961829);
        public static readonly CilOpCode Ldind_I4 = new CilOpCode(CilCode.Ldind_I4, 6961829);
        public static readonly CilOpCode Ldind_U4 = new CilOpCode(CilCode.Ldind_U4, 6961829);
        public static readonly CilOpCode Ldind_I8 = new CilOpCode(CilCode.Ldind_I8, 7092901);
        public static readonly CilOpCode Ldind_I = new CilOpCode(CilCode.Ldind_I, 6961829);
        public static readonly CilOpCode Ldind_R4 = new CilOpCode(CilCode.Ldind_R4, 7223973);
        public static readonly CilOpCode Ldind_R8 = new CilOpCode(CilCode.Ldind_R8, 7355045);
        public static readonly CilOpCode Ldind_Ref = new CilOpCode(CilCode.Ldind_Ref, 7486117);
        public static readonly CilOpCode Stind_Ref = new CilOpCode(CilCode.Stind_Ref, -530294107);
        public static readonly CilOpCode Stind_I1 = new CilOpCode(CilCode.Stind_I1, -530294107);
        public static readonly CilOpCode Stind_I2 = new CilOpCode(CilCode.Stind_I2, -530294107);
        public static readonly CilOpCode Stind_I4 = new CilOpCode(CilCode.Stind_I4, -530294107);
        public static readonly CilOpCode Stind_I8 = new CilOpCode(CilCode.Stind_I8, -530290011);
        public static readonly CilOpCode Stind_R4 = new CilOpCode(CilCode.Stind_R4, -530281819);
        public static readonly CilOpCode Stind_R8 = new CilOpCode(CilCode.Stind_R8, -530277723);
        public static readonly CilOpCode Add = new CilOpCode(CilCode.Add, -261739867);
        public static readonly CilOpCode Sub = new CilOpCode(CilCode.Sub, -261739867);
        public static readonly CilOpCode Mul = new CilOpCode(CilCode.Mul, -261739867);
        public static readonly CilOpCode Div = new CilOpCode(CilCode.Div, -261739867);
        public static readonly CilOpCode Div_Un = new CilOpCode(CilCode.Div_Un, -261739867);
        public static readonly CilOpCode Rem = new CilOpCode(CilCode.Rem, -261739867);
        public static readonly CilOpCode Rem_Un = new CilOpCode(CilCode.Rem_Un, -261739867);
        public static readonly CilOpCode And = new CilOpCode(CilCode.And, -261739867);
        public static readonly CilOpCode Or = new CilOpCode(CilCode.Or, -261739867);
        public static readonly CilOpCode Xor = new CilOpCode(CilCode.Xor, -261739867);
        public static readonly CilOpCode Shl = new CilOpCode(CilCode.Shl, -261739867);
        public static readonly CilOpCode Shr = new CilOpCode(CilCode.Shr, -261739867);
        public static readonly CilOpCode Shr_Un = new CilOpCode(CilCode.Shr_Un, -261739867);
        public static readonly CilOpCode Neg = new CilOpCode(CilCode.Neg, 6691493);
        public static readonly CilOpCode Not = new CilOpCode(CilCode.Not, 6691493);
        public static readonly CilOpCode Conv_I1 = new CilOpCode(CilCode.Conv_I1, 6953637);
        public static readonly CilOpCode Conv_I2 = new CilOpCode(CilCode.Conv_I2, 6953637);
        public static readonly CilOpCode Conv_I4 = new CilOpCode(CilCode.Conv_I4, 6953637);
        public static readonly CilOpCode Conv_I8 = new CilOpCode(CilCode.Conv_I8, 7084709);
        public static readonly CilOpCode Conv_R4 = new CilOpCode(CilCode.Conv_R4, 7215781);
        public static readonly CilOpCode Conv_R8 = new CilOpCode(CilCode.Conv_R8, 7346853);
        public static readonly CilOpCode Conv_U4 = new CilOpCode(CilCode.Conv_U4, 6953637);
        public static readonly CilOpCode Conv_U8 = new CilOpCode(CilCode.Conv_U8, 7084709);
        public static readonly CilOpCode Callvirt = new CilOpCode(CilCode.Callvirt, 7841348);
        public static readonly CilOpCode Cpobj = new CilOpCode(CilCode.Cpobj, -530295123);
        public static readonly CilOpCode Ldobj = new CilOpCode(CilCode.Ldobj, 6698669);
        public static readonly CilOpCode Ldstr = new CilOpCode(CilCode.Ldstr, 275908266);
        public static readonly CilOpCode Newobj = new CilOpCode(CilCode.Newobj, 276014660);
        public static readonly CilOpCode Castclass = new CilOpCode(CilCode.Castclass, 7513773);
        public static readonly CilOpCode Isinst = new CilOpCode(CilCode.Isinst, 6989485);
        public static readonly CilOpCode Conv_R_Un = new CilOpCode(CilCode.Conv_R_Un, 7346853);
        public static readonly CilOpCode Unbox = new CilOpCode(CilCode.Unbox, 6990509);
        public static readonly CilOpCode Throw = new CilOpCode(CilCode.Throw, -245061883);
        public static readonly CilOpCode Ldfld = new CilOpCode(CilCode.Ldfld, 6727329);
        public static readonly CilOpCode Ldflda = new CilOpCode(CilCode.Ldflda, 6989473);
        public static readonly CilOpCode Stfld = new CilOpCode(CilCode.Stfld, -530270559);
        public static readonly CilOpCode Ldsfld = new CilOpCode(CilCode.Ldsfld, 275121825);
        public static readonly CilOpCode Ldsflda = new CilOpCode(CilCode.Ldsflda, 275383969);
        public static readonly CilOpCode Stsfld = new CilOpCode(CilCode.Stsfld, -261876063);
        public static readonly CilOpCode Stobj = new CilOpCode(CilCode.Stobj, -530298195);
        public static readonly CilOpCode Conv_Ovf_I1_Un = new CilOpCode(CilCode.Conv_Ovf_I1_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_I2_Un = new CilOpCode(CilCode.Conv_Ovf_I2_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_I4_Un = new CilOpCode(CilCode.Conv_Ovf_I4_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_I8_Un = new CilOpCode(CilCode.Conv_Ovf_I8_Un, 7084709);
        public static readonly CilOpCode Conv_Ovf_U1_Un = new CilOpCode(CilCode.Conv_Ovf_U1_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_U2_Un = new CilOpCode(CilCode.Conv_Ovf_U2_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_U4_Un = new CilOpCode(CilCode.Conv_Ovf_U4_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_U8_Un = new CilOpCode(CilCode.Conv_Ovf_U8_Un, 7084709);
        public static readonly CilOpCode Conv_Ovf_I_Un = new CilOpCode(CilCode.Conv_Ovf_I_Un, 6953637);
        public static readonly CilOpCode Conv_Ovf_U_Un = new CilOpCode(CilCode.Conv_Ovf_U_Un, 6953637);
        public static readonly CilOpCode Box = new CilOpCode(CilCode.Box, 7477933);
        public static readonly CilOpCode Newarr = new CilOpCode(CilCode.Newarr, 7485101);
        public static readonly CilOpCode Ldlen = new CilOpCode(CilCode.Ldlen, 6989477);
        public static readonly CilOpCode Ldelema = new CilOpCode(CilCode.Ldelema, -261437779);
        public static readonly CilOpCode Ldelem_I1 = new CilOpCode(CilCode.Ldelem_I1, -261437787);
        public static readonly CilOpCode Ldelem_U1 = new CilOpCode(CilCode.Ldelem_U1, -261437787);
        public static readonly CilOpCode Ldelem_I2 = new CilOpCode(CilCode.Ldelem_I2, -261437787);
        public static readonly CilOpCode Ldelem_U2 = new CilOpCode(CilCode.Ldelem_U2, -261437787);
        public static readonly CilOpCode Ldelem_I4 = new CilOpCode(CilCode.Ldelem_I4, -261437787);
        public static readonly CilOpCode Ldelem_U4 = new CilOpCode(CilCode.Ldelem_U4, -261437787);
        public static readonly CilOpCode Ldelem_I8 = new CilOpCode(CilCode.Ldelem_I8, -261306715);
        public static readonly CilOpCode Ldelem_I = new CilOpCode(CilCode.Ldelem_I, -261437787);
        public static readonly CilOpCode Ldelem_R4 = new CilOpCode(CilCode.Ldelem_R4, -261175643);
        public static readonly CilOpCode Ldelem_R8 = new CilOpCode(CilCode.Ldelem_R8, -261044571);
        public static readonly CilOpCode Ldelem_Ref = new CilOpCode(CilCode.Ldelem_Ref, -260913499);
        public static readonly CilOpCode Stelem_I = new CilOpCode(CilCode.Stelem_I, -798697819);
        public static readonly CilOpCode Stelem_I1 = new CilOpCode(CilCode.Stelem_I1, -798697819);
        public static readonly CilOpCode Stelem_I2 = new CilOpCode(CilCode.Stelem_I2, -798697819);
        public static readonly CilOpCode Stelem_I4 = new CilOpCode(CilCode.Stelem_I4, -798697819);
        public static readonly CilOpCode Stelem_I8 = new CilOpCode(CilCode.Stelem_I8, -798693723);
        public static readonly CilOpCode Stelem_R4 = new CilOpCode(CilCode.Stelem_R4, -798689627);
        public static readonly CilOpCode Stelem_R8 = new CilOpCode(CilCode.Stelem_R8, -798685531);
        public static readonly CilOpCode Stelem_Ref = new CilOpCode(CilCode.Stelem_Ref, -798681435);
        public static readonly CilOpCode Ldelem = new CilOpCode(CilCode.Ldelem, -261699923);
        public static readonly CilOpCode Stelem = new CilOpCode(CilCode.Stelem, 6669997);
        public static readonly CilOpCode Unbox_Any = new CilOpCode(CilCode.Unbox_Any, 6727341);
        public static readonly CilOpCode Conv_Ovf_I1 = new CilOpCode(CilCode.Conv_Ovf_I1, 6953637);
        public static readonly CilOpCode Conv_Ovf_U1 = new CilOpCode(CilCode.Conv_Ovf_U1, 6953637);
        public static readonly CilOpCode Conv_Ovf_I2 = new CilOpCode(CilCode.Conv_Ovf_I2, 6953637);
        public static readonly CilOpCode Conv_Ovf_U2 = new CilOpCode(CilCode.Conv_Ovf_U2, 6953637);
        public static readonly CilOpCode Conv_Ovf_I4 = new CilOpCode(CilCode.Conv_Ovf_I4, 6953637);
        public static readonly CilOpCode Conv_Ovf_U4 = new CilOpCode(CilCode.Conv_Ovf_U4, 6953637);
        public static readonly CilOpCode Conv_Ovf_I8 = new CilOpCode(CilCode.Conv_Ovf_I8, 7084709);
        public static readonly CilOpCode Conv_Ovf_U8 = new CilOpCode(CilCode.Conv_Ovf_U8, 7084709);
        public static readonly CilOpCode Refanyval = new CilOpCode(CilCode.Refanyval, 6953645);
        public static readonly CilOpCode Ckfinite = new CilOpCode(CilCode.Ckfinite, 7346853);
        public static readonly CilOpCode Mkrefany = new CilOpCode(CilCode.Mkrefany, 6699693);
        public static readonly CilOpCode Ldtoken = new CilOpCode(CilCode.Ldtoken, 275385004);
        public static readonly CilOpCode Conv_U2 = new CilOpCode(CilCode.Conv_U2, 6953637);
        public static readonly CilOpCode Conv_U1 = new CilOpCode(CilCode.Conv_U1, 6953637);
        public static readonly CilOpCode Conv_I = new CilOpCode(CilCode.Conv_I, 6953637);
        public static readonly CilOpCode Conv_Ovf_I = new CilOpCode(CilCode.Conv_Ovf_I, 6953637);
        public static readonly CilOpCode Conv_Ovf_U = new CilOpCode(CilCode.Conv_Ovf_U, 6953637);
        public static readonly CilOpCode Add_Ovf = new CilOpCode(CilCode.Add_Ovf, -261739867);
        public static readonly CilOpCode Add_Ovf_Un = new CilOpCode(CilCode.Add_Ovf_Un, -261739867);
        public static readonly CilOpCode Mul_Ovf = new CilOpCode(CilCode.Mul_Ovf, -261739867);
        public static readonly CilOpCode Mul_Ovf_Un = new CilOpCode(CilCode.Mul_Ovf_Un, -261739867);
        public static readonly CilOpCode Sub_Ovf = new CilOpCode(CilCode.Sub_Ovf, -261739867);
        public static readonly CilOpCode Sub_Ovf_Un = new CilOpCode(CilCode.Sub_Ovf_Un, -261739867);
        public static readonly CilOpCode Endfinally = new CilOpCode(CilCode.Endfinally, 23333605);
        public static readonly CilOpCode Leave = new CilOpCode(CilCode.Leave, 23333376);
        public static readonly CilOpCode Leave_S = new CilOpCode(CilCode.Leave_S, 23333391);
        public static readonly CilOpCode Stind_I = new CilOpCode(CilCode.Stind_I, -530294107);
        public static readonly CilOpCode Conv_U = new CilOpCode(CilCode.Conv_U, 6953637);
        public static readonly CilOpCode Prefix7 = new CilOpCode(CilCode.Prefix7, 6554757);
        public static readonly CilOpCode Prefix6 = new CilOpCode(CilCode.Prefix6, 6554757);
        public static readonly CilOpCode Prefix5 = new CilOpCode(CilCode.Prefix5, 6554757);
        public static readonly CilOpCode Prefix4 = new CilOpCode(CilCode.Prefix4, 6554757);
        public static readonly CilOpCode Prefix3 = new CilOpCode(CilCode.Prefix3, 6554757);
        public static readonly CilOpCode Prefix2 = new CilOpCode(CilCode.Prefix2, 6554757);
        public static readonly CilOpCode Prefix1 = new CilOpCode(CilCode.Prefix1, 6554757);
        public static readonly CilOpCode Prefixref = new CilOpCode(CilCode.Prefixref, 6554757);
        public static readonly CilOpCode Arglist = new CilOpCode(CilCode.Arglist, 279579301);
        public static readonly CilOpCode Ceq = new CilOpCode(CilCode.Ceq, -257283419);
        public static readonly CilOpCode Cgt = new CilOpCode(CilCode.Cgt, -257283419);
        public static readonly CilOpCode Cgt_Un = new CilOpCode(CilCode.Cgt_Un, -257283419);
        public static readonly CilOpCode Clt = new CilOpCode(CilCode.Clt, -257283419);
        public static readonly CilOpCode Clt_Un = new CilOpCode(CilCode.Clt_Un, -257283419);
        public static readonly CilOpCode Ldftn = new CilOpCode(CilCode.Ldftn, 279579300);
        public static readonly CilOpCode Ldvirtftn = new CilOpCode(CilCode.Ldvirtftn, 11184804);
        public static readonly CilOpCode Ldarg = new CilOpCode(CilCode.Ldarg, 279317171);
        public static readonly CilOpCode Ldarga = new CilOpCode(CilCode.Ldarga, 279579315);
        public static readonly CilOpCode Starg = new CilOpCode(CilCode.Starg, -257680717);
        public static readonly CilOpCode Ldloc = new CilOpCode(CilCode.Ldloc, 279317166);
        public static readonly CilOpCode Ldloca = new CilOpCode(CilCode.Ldloca, 279579310);
        public static readonly CilOpCode Stloc = new CilOpCode(CilCode.Stloc, -257680722);
        public static readonly CilOpCode Localloc = new CilOpCode(CilCode.Localloc, 11156133);
        public static readonly CilOpCode Endfilter = new CilOpCode(CilCode.Endfilter, -240895259);
        public static readonly CilOpCode Unaligned = new CilOpCode(CilCode.Unaligned, 10750096);
        public static readonly CilOpCode Volatile = new CilOpCode(CilCode.Volatile, 10750085);
        public static readonly CilOpCode Tail = new CilOpCode(CilCode.Tail, 10750085);
        public static readonly CilOpCode Initobj = new CilOpCode(CilCode.Initobj, -257673555);
        public static readonly CilOpCode Constrained = new CilOpCode(CilCode.Constrained, 10750093);
        public static readonly CilOpCode Cpblk = new CilOpCode(CilCode.Cpblk, -794527067);
        public static readonly CilOpCode Initblk = new CilOpCode(CilCode.Initblk, -794527067);
        public static readonly CilOpCode Rethrow = new CilOpCode(CilCode.Rethrow, 27526917);
        public static readonly CilOpCode Sizeof = new CilOpCode(CilCode.Sizeof, 279579309);
        public static readonly CilOpCode Refanytype = new CilOpCode(CilCode.Refanytype, 11147941);
        public static readonly CilOpCode Readonly = new CilOpCode(CilCode.Readonly, 10750085);

        // ReSharper restore InconsistentNaming
    }
}
