name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
      placeholder: |
        Example: "I'm always frustrated when [...]", or "I often need to [...]"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        A clear and concise description of what you want to happen. You can be relatively open-ended, but including
        syntax suggestions or pseudo code is appreciated as it may help conveying your idea.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
