<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>AsmResolver.PE</Title>
    <Description>PE image models for the AsmResolver executable file inspection toolsuite.</Description>
    <PackageTags>exe pe directories imports exports resources dotnet cil inspection manipulation assembly disassembly</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IsExternalInit" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsmResolver.PE.File\AsmResolver.PE.File.csproj" />
    <ProjectReference
      Include="..\..\tools\AsmResolver.SourceGenerators\AsmResolver.SourceGenerators.csproj"
      ReferenceOutputAssembly="false"
      OutputItemType="Analyzer"
      SetTargetFramework="TargetFramework=netstandard2.0"
    />
  </ItemGroup>

</Project>
