//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmResolver.DotNet.TestCases.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsmResolver.DotNet.TestCases.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool BoolFalse {
            get {
                object obj = ResourceManager.GetObject("BoolFalse", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool BoolTrue {
            get {
                object obj = ResourceManager.GetObject("BoolTrue", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte similar to 18.
        /// </summary>
        internal static byte Byte {
            get {
                object obj = ResourceManager.GetObject("Byte", resourceCulture);
                return ((byte)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ByteArray {
            get {
                object obj = ResourceManager.GetObject("ByteArray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to a.
        /// </summary>
        internal static char Char {
            get {
                object obj = ResourceManager.GetObject("Char", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.DateTime similar to 02/01/2021 00:00:00.
        /// </summary>
        internal static System.DateTime DateTime {
            get {
                object obj = ResourceManager.GetObject("DateTime", resourceCulture);
                return ((System.DateTime)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Double similar to 1.234.
        /// </summary>
        internal static double Double {
            get {
                object obj = ResourceManager.GetObject("Double", resourceCulture);
                return ((double)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int16 similar to 4660.
        /// </summary>
        internal static short Int16 {
            get {
                object obj = ResourceManager.GetObject("Int16", resourceCulture);
                return ((short)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 305419896.
        /// </summary>
        internal static int Int32 {
            get {
                object obj = ResourceManager.GetObject("Int32", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int64 similar to 81985529216486895.
        /// </summary>
        internal static long Int64 {
            get {
                object obj = ResourceManager.GetObject("Int64", resourceCulture);
                return ((long)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Null {
            get {
                object obj = ResourceManager.GetObject("Null", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.SByte similar to 18.
        /// </summary>
        internal static sbyte SByte {
            get {
                object obj = ResourceManager.GetObject("SByte", resourceCulture);
                return ((sbyte)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Single similar to 1.234.
        /// </summary>
        internal static float Single {
            get {
                object obj = ResourceManager.GetObject("Single", resourceCulture);
                return ((float)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.TimeSpan similar to 10:01:02.
        /// </summary>
        internal static System.TimeSpan TimeSpan {
            get {
                object obj = ResourceManager.GetObject("TimeSpan", resourceCulture);
                return ((System.TimeSpan)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.UInt16 similar to 4660.
        /// </summary>
        internal static ushort UInt16 {
            get {
                object obj = ResourceManager.GetObject("UInt16", resourceCulture);
                return ((ushort)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.UInt32 similar to 305419896.
        /// </summary>
        internal static uint UInt32 {
            get {
                object obj = ResourceManager.GetObject("UInt32", resourceCulture);
                return ((uint)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.UInt64 similar to 81985529216486895.
        /// </summary>
        internal static ulong UInt64 {
            get {
                object obj = ResourceManager.GetObject("UInt64", resourceCulture);
                return ((ulong)(obj));
            }
        }
    }
}
