//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmResolver.PE.File.Tests.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AsmResolver.PE.File.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] HelloWorld {
            get {
                object obj = ResourceManager.GetObject("HelloWorld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelloWorldDump {
            get {
                object obj = ResourceManager.GetObject("HelloWorldDump", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelloWorld_EOF {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_EOF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelloWorld_InvalidSectionName {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_InvalidSectionName", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HelloWorld_ExtraSectionData {
            get {
                object obj = ResourceManager.GetObject("HelloWorld_ExtraSectionData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NativeMemoryDemos {
            get {
                object obj = ResourceManager.GetObject("NativeMemoryDemos", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
