using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AsmResolver.Net.Msil
{
    public static class MsilOpCodes
    {
        public static readonly MsilOpCode[] SingleByteOpCodes = new MsilOpCode[256];
        public static readonly MsilOpCode[] MultiByteOpCodes = new MsilOpCode[256];

        public static MsilOpCode GetOpCode(MsilCode code)
        {
            var value = (int)code;
            if ((value & 0xFE00) == 0xFE00)
                return MultiByteOpCodes[value & 0xFF];
            return SingleByteOpCodes[value & 0xFF];
        }

        public static MsilOpCode GetOpCode(string name)
        {
            return SingleByteOpCodes.Concat(MultiByteOpCodes).First(x => x.Name == name);
        }

        // taken from the System.Reflection.Emit.OpCodes class (except for InlineArgument opcodes).
        // ReSharper disable InconsistentNaming

        public static readonly MsilOpCode Nop = new MsilOpCode(MsilCode.Nop, 6556325);
        public static readonly MsilOpCode Break = new MsilOpCode(MsilCode.Break, 6556197);
        public static readonly MsilOpCode Ldarg_0 = new MsilOpCode(MsilCode.Ldarg_0, 275120805);
        public static readonly MsilOpCode Ldarg_1 = new MsilOpCode(MsilCode.Ldarg_1, 275120805);
        public static readonly MsilOpCode Ldarg_2 = new MsilOpCode(MsilCode.Ldarg_2, 275120805);
        public static readonly MsilOpCode Ldarg_3 = new MsilOpCode(MsilCode.Ldarg_3, 275120805);
        public static readonly MsilOpCode Ldloc_0 = new MsilOpCode(MsilCode.Ldloc_0, 275120805);
        public static readonly MsilOpCode Ldloc_1 = new MsilOpCode(MsilCode.Ldloc_1, 275120805);
        public static readonly MsilOpCode Ldloc_2 = new MsilOpCode(MsilCode.Ldloc_2, 275120805);
        public static readonly MsilOpCode Ldloc_3 = new MsilOpCode(MsilCode.Ldloc_3, 275120805);
        public static readonly MsilOpCode Stloc_0 = new MsilOpCode(MsilCode.Stloc_0, -261877083);
        public static readonly MsilOpCode Stloc_1 = new MsilOpCode(MsilCode.Stloc_1, -261877083);
        public static readonly MsilOpCode Stloc_2 = new MsilOpCode(MsilCode.Stloc_2, -261877083);
        public static readonly MsilOpCode Stloc_3 = new MsilOpCode(MsilCode.Stloc_3, -261877083);
        public static readonly MsilOpCode Ldarg_S = new MsilOpCode(MsilCode.Ldarg_S, 275120820);
        public static readonly MsilOpCode Ldarga_S = new MsilOpCode(MsilCode.Ldarga_S, 275382964);
        public static readonly MsilOpCode Starg_S = new MsilOpCode(MsilCode.Starg_S, -261877068);
        public static readonly MsilOpCode Ldloc_S = new MsilOpCode(MsilCode.Ldloc_S, 275120818);
        public static readonly MsilOpCode Ldloca_S = new MsilOpCode(MsilCode.Ldloca_S, 275382962);
        public static readonly MsilOpCode Stloc_S = new MsilOpCode(MsilCode.Stloc_S, -261877070);
        public static readonly MsilOpCode Ldnull = new MsilOpCode(MsilCode.Ldnull, 275909285);
        public static readonly MsilOpCode Ldc_I4_M1 = new MsilOpCode(MsilCode.Ldc_I4_M1, 275382949);
        public static readonly MsilOpCode Ldc_I4_0 = new MsilOpCode(MsilCode.Ldc_I4_0, 275382949);
        public static readonly MsilOpCode Ldc_I4_1 = new MsilOpCode(MsilCode.Ldc_I4_1, 275382949);
        public static readonly MsilOpCode Ldc_I4_2 = new MsilOpCode(MsilCode.Ldc_I4_2, 275382949);
        public static readonly MsilOpCode Ldc_I4_3 = new MsilOpCode(MsilCode.Ldc_I4_3, 275382949);
        public static readonly MsilOpCode Ldc_I4_4 = new MsilOpCode(MsilCode.Ldc_I4_4, 275382949);
        public static readonly MsilOpCode Ldc_I4_5 = new MsilOpCode(MsilCode.Ldc_I4_5, 275382949);
        public static readonly MsilOpCode Ldc_I4_6 = new MsilOpCode(MsilCode.Ldc_I4_6, 275382949);
        public static readonly MsilOpCode Ldc_I4_7 = new MsilOpCode(MsilCode.Ldc_I4_7, 275382949);
        public static readonly MsilOpCode Ldc_I4_8 = new MsilOpCode(MsilCode.Ldc_I4_8, 275382949);
        public static readonly MsilOpCode Ldc_I4_S = new MsilOpCode(MsilCode.Ldc_I4_S, 275382960);
        public static readonly MsilOpCode Ldc_I4 = new MsilOpCode(MsilCode.Ldc_I4, 275384994);
        public static readonly MsilOpCode Ldc_I8 = new MsilOpCode(MsilCode.Ldc_I8, 275516067);
        public static readonly MsilOpCode Ldc_R4 = new MsilOpCode(MsilCode.Ldc_R4, 275647153);
        public static readonly MsilOpCode Ldc_R8 = new MsilOpCode(MsilCode.Ldc_R8, 275778215);
        public static readonly MsilOpCode Dup = new MsilOpCode(MsilCode.Dup, 275258021);
        public static readonly MsilOpCode Pop = new MsilOpCode(MsilCode.Pop, -261875035);
        public static readonly MsilOpCode Jmp = new MsilOpCode(MsilCode.Jmp, 23333444);
        public static readonly MsilOpCode Call = new MsilOpCode(MsilCode.Call, 7842372);
        public static readonly MsilOpCode Calli = new MsilOpCode(MsilCode.Calli, 7842377);
        public static readonly MsilOpCode Ret = new MsilOpCode(MsilCode.Ret, 23440101);
        public static readonly MsilOpCode Br_S = new MsilOpCode(MsilCode.Br_S, 23331343);
        public static readonly MsilOpCode Brfalse_S = new MsilOpCode(MsilCode.Brfalse_S, -261868945);
        public static readonly MsilOpCode Brtrue_S = new MsilOpCode(MsilCode.Brtrue_S, -261868945);
        public static readonly MsilOpCode Beq_S = new MsilOpCode(MsilCode.Beq_S, -530308497);
        public static readonly MsilOpCode Bge_S = new MsilOpCode(MsilCode.Bge_S, -530308497);
        public static readonly MsilOpCode Bgt_S = new MsilOpCode(MsilCode.Bgt_S, -530308497);
        public static readonly MsilOpCode Ble_S = new MsilOpCode(MsilCode.Ble_S, -530308497);
        public static readonly MsilOpCode Blt_S = new MsilOpCode(MsilCode.Blt_S, -530308497);
        public static readonly MsilOpCode Bne_Un_S = new MsilOpCode(MsilCode.Bne_Un_S, -530308497);
        public static readonly MsilOpCode Bge_Un_S = new MsilOpCode(MsilCode.Bge_Un_S, -530308497);
        public static readonly MsilOpCode Bgt_Un_S = new MsilOpCode(MsilCode.Bgt_Un_S, -530308497);
        public static readonly MsilOpCode Ble_Un_S = new MsilOpCode(MsilCode.Ble_Un_S, -530308497);
        public static readonly MsilOpCode Blt_Un_S = new MsilOpCode(MsilCode.Blt_Un_S, -530308497);
        public static readonly MsilOpCode Br = new MsilOpCode(MsilCode.Br, 23333376);
        public static readonly MsilOpCode Brfalse = new MsilOpCode(MsilCode.Brfalse, -261866912);
        public static readonly MsilOpCode Brtrue = new MsilOpCode(MsilCode.Brtrue, -261866912);
        public static readonly MsilOpCode Beq = new MsilOpCode(MsilCode.Beq, -530308512);
        public static readonly MsilOpCode Bge = new MsilOpCode(MsilCode.Bge, -530308512);
        public static readonly MsilOpCode Bgt = new MsilOpCode(MsilCode.Bgt, -530308512);
        public static readonly MsilOpCode Ble = new MsilOpCode(MsilCode.Ble, -530308512);
        public static readonly MsilOpCode Blt = new MsilOpCode(MsilCode.Blt, -530308512);
        public static readonly MsilOpCode Bne_Un = new MsilOpCode(MsilCode.Bne_Un, -530308512);
        public static readonly MsilOpCode Bge_Un = new MsilOpCode(MsilCode.Bge_Un, -530308512);
        public static readonly MsilOpCode Bgt_Un = new MsilOpCode(MsilCode.Bgt_Un, -530308512);
        public static readonly MsilOpCode Ble_Un = new MsilOpCode(MsilCode.Ble_Un, -530308512);
        public static readonly MsilOpCode Blt_Un = new MsilOpCode(MsilCode.Blt_Un, -530308512);
        public static readonly MsilOpCode Switch = new MsilOpCode(MsilCode.Switch, -261866901);
        public static readonly MsilOpCode Ldind_I1 = new MsilOpCode(MsilCode.Ldind_I1, 6961829);
        public static readonly MsilOpCode Ldind_U1 = new MsilOpCode(MsilCode.Ldind_U1, 6961829);
        public static readonly MsilOpCode Ldind_I2 = new MsilOpCode(MsilCode.Ldind_I2, 6961829);
        public static readonly MsilOpCode Ldind_U2 = new MsilOpCode(MsilCode.Ldind_U2, 6961829);
        public static readonly MsilOpCode Ldind_I4 = new MsilOpCode(MsilCode.Ldind_I4, 6961829);
        public static readonly MsilOpCode Ldind_U4 = new MsilOpCode(MsilCode.Ldind_U4, 6961829);
        public static readonly MsilOpCode Ldind_I8 = new MsilOpCode(MsilCode.Ldind_I8, 7092901);
        public static readonly MsilOpCode Ldind_I = new MsilOpCode(MsilCode.Ldind_I, 6961829);
        public static readonly MsilOpCode Ldind_R4 = new MsilOpCode(MsilCode.Ldind_R4, 7223973);
        public static readonly MsilOpCode Ldind_R8 = new MsilOpCode(MsilCode.Ldind_R8, 7355045);
        public static readonly MsilOpCode Ldind_Ref = new MsilOpCode(MsilCode.Ldind_Ref, 7486117);
        public static readonly MsilOpCode Stind_Ref = new MsilOpCode(MsilCode.Stind_Ref, -530294107);
        public static readonly MsilOpCode Stind_I1 = new MsilOpCode(MsilCode.Stind_I1, -530294107);
        public static readonly MsilOpCode Stind_I2 = new MsilOpCode(MsilCode.Stind_I2, -530294107);
        public static readonly MsilOpCode Stind_I4 = new MsilOpCode(MsilCode.Stind_I4, -530294107);
        public static readonly MsilOpCode Stind_I8 = new MsilOpCode(MsilCode.Stind_I8, -530290011);
        public static readonly MsilOpCode Stind_R4 = new MsilOpCode(MsilCode.Stind_R4, -530281819);
        public static readonly MsilOpCode Stind_R8 = new MsilOpCode(MsilCode.Stind_R8, -530277723);
        public static readonly MsilOpCode Add = new MsilOpCode(MsilCode.Add, -261739867);
        public static readonly MsilOpCode Sub = new MsilOpCode(MsilCode.Sub, -261739867);
        public static readonly MsilOpCode Mul = new MsilOpCode(MsilCode.Mul, -261739867);
        public static readonly MsilOpCode Div = new MsilOpCode(MsilCode.Div, -261739867);
        public static readonly MsilOpCode Div_Un = new MsilOpCode(MsilCode.Div_Un, -261739867);
        public static readonly MsilOpCode Rem = new MsilOpCode(MsilCode.Rem, -261739867);
        public static readonly MsilOpCode Rem_Un = new MsilOpCode(MsilCode.Rem_Un, -261739867);
        public static readonly MsilOpCode And = new MsilOpCode(MsilCode.And, -261739867);
        public static readonly MsilOpCode Or = new MsilOpCode(MsilCode.Or, -261739867);
        public static readonly MsilOpCode Xor = new MsilOpCode(MsilCode.Xor, -261739867);
        public static readonly MsilOpCode Shl = new MsilOpCode(MsilCode.Shl, -261739867);
        public static readonly MsilOpCode Shr = new MsilOpCode(MsilCode.Shr, -261739867);
        public static readonly MsilOpCode Shr_Un = new MsilOpCode(MsilCode.Shr_Un, -261739867);
        public static readonly MsilOpCode Neg = new MsilOpCode(MsilCode.Neg, 6691493);
        public static readonly MsilOpCode Not = new MsilOpCode(MsilCode.Not, 6691493);
        public static readonly MsilOpCode Conv_I1 = new MsilOpCode(MsilCode.Conv_I1, 6953637);
        public static readonly MsilOpCode Conv_I2 = new MsilOpCode(MsilCode.Conv_I2, 6953637);
        public static readonly MsilOpCode Conv_I4 = new MsilOpCode(MsilCode.Conv_I4, 6953637);
        public static readonly MsilOpCode Conv_I8 = new MsilOpCode(MsilCode.Conv_I8, 7084709);
        public static readonly MsilOpCode Conv_R4 = new MsilOpCode(MsilCode.Conv_R4, 7215781);
        public static readonly MsilOpCode Conv_R8 = new MsilOpCode(MsilCode.Conv_R8, 7346853);
        public static readonly MsilOpCode Conv_U4 = new MsilOpCode(MsilCode.Conv_U4, 6953637);
        public static readonly MsilOpCode Conv_U8 = new MsilOpCode(MsilCode.Conv_U8, 7084709);
        public static readonly MsilOpCode Callvirt = new MsilOpCode(MsilCode.Callvirt, 7841348);
        public static readonly MsilOpCode Cpobj = new MsilOpCode(MsilCode.Cpobj, -530295123);
        public static readonly MsilOpCode Ldobj = new MsilOpCode(MsilCode.Ldobj, 6698669);
        public static readonly MsilOpCode Ldstr = new MsilOpCode(MsilCode.Ldstr, 275908266);
        public static readonly MsilOpCode Newobj = new MsilOpCode(MsilCode.Newobj, 276014660);
        public static readonly MsilOpCode Castclass = new MsilOpCode(MsilCode.Castclass, 7513773);
        public static readonly MsilOpCode Isinst = new MsilOpCode(MsilCode.Isinst, 6989485);
        public static readonly MsilOpCode Conv_R_Un = new MsilOpCode(MsilCode.Conv_R_Un, 7346853);
        public static readonly MsilOpCode Unbox = new MsilOpCode(MsilCode.Unbox, 6990509);
        public static readonly MsilOpCode Throw = new MsilOpCode(MsilCode.Throw, -245061883);
        public static readonly MsilOpCode Ldfld = new MsilOpCode(MsilCode.Ldfld, 6727329);
        public static readonly MsilOpCode Ldflda = new MsilOpCode(MsilCode.Ldflda, 6989473);
        public static readonly MsilOpCode Stfld = new MsilOpCode(MsilCode.Stfld, -530270559);
        public static readonly MsilOpCode Ldsfld = new MsilOpCode(MsilCode.Ldsfld, 275121825);
        public static readonly MsilOpCode Ldsflda = new MsilOpCode(MsilCode.Ldsflda, 275383969);
        public static readonly MsilOpCode Stsfld = new MsilOpCode(MsilCode.Stsfld, -261876063);
        public static readonly MsilOpCode Stobj = new MsilOpCode(MsilCode.Stobj, -530298195);
        public static readonly MsilOpCode Conv_Ovf_I1_Un = new MsilOpCode(MsilCode.Conv_Ovf_I1_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I2_Un = new MsilOpCode(MsilCode.Conv_Ovf_I2_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I4_Un = new MsilOpCode(MsilCode.Conv_Ovf_I4_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I8_Un = new MsilOpCode(MsilCode.Conv_Ovf_I8_Un, 7084709);
        public static readonly MsilOpCode Conv_Ovf_U1_Un = new MsilOpCode(MsilCode.Conv_Ovf_U1_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U2_Un = new MsilOpCode(MsilCode.Conv_Ovf_U2_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U4_Un = new MsilOpCode(MsilCode.Conv_Ovf_U4_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U8_Un = new MsilOpCode(MsilCode.Conv_Ovf_U8_Un, 7084709);
        public static readonly MsilOpCode Conv_Ovf_I_Un = new MsilOpCode(MsilCode.Conv_Ovf_I_Un, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U_Un = new MsilOpCode(MsilCode.Conv_Ovf_U_Un, 6953637);
        public static readonly MsilOpCode Box = new MsilOpCode(MsilCode.Box, 7477933);
        public static readonly MsilOpCode Newarr = new MsilOpCode(MsilCode.Newarr, 7485101);
        public static readonly MsilOpCode Ldlen = new MsilOpCode(MsilCode.Ldlen, 6989477);
        public static readonly MsilOpCode Ldelema = new MsilOpCode(MsilCode.Ldelema, -261437779);
        public static readonly MsilOpCode Ldelem_I1 = new MsilOpCode(MsilCode.Ldelem_I1, -261437787);
        public static readonly MsilOpCode Ldelem_U1 = new MsilOpCode(MsilCode.Ldelem_U1, -261437787);
        public static readonly MsilOpCode Ldelem_I2 = new MsilOpCode(MsilCode.Ldelem_I2, -261437787);
        public static readonly MsilOpCode Ldelem_U2 = new MsilOpCode(MsilCode.Ldelem_U2, -261437787);
        public static readonly MsilOpCode Ldelem_I4 = new MsilOpCode(MsilCode.Ldelem_I4, -261437787);
        public static readonly MsilOpCode Ldelem_U4 = new MsilOpCode(MsilCode.Ldelem_U4, -261437787);
        public static readonly MsilOpCode Ldelem_I8 = new MsilOpCode(MsilCode.Ldelem_I8, -261306715);
        public static readonly MsilOpCode Ldelem_I = new MsilOpCode(MsilCode.Ldelem_I, -261437787);
        public static readonly MsilOpCode Ldelem_R4 = new MsilOpCode(MsilCode.Ldelem_R4, -261175643);
        public static readonly MsilOpCode Ldelem_R8 = new MsilOpCode(MsilCode.Ldelem_R8, -261044571);
        public static readonly MsilOpCode Ldelem_Ref = new MsilOpCode(MsilCode.Ldelem_Ref, -260913499);
        public static readonly MsilOpCode Stelem_I = new MsilOpCode(MsilCode.Stelem_I, -798697819);
        public static readonly MsilOpCode Stelem_I1 = new MsilOpCode(MsilCode.Stelem_I1, -798697819);
        public static readonly MsilOpCode Stelem_I2 = new MsilOpCode(MsilCode.Stelem_I2, -798697819);
        public static readonly MsilOpCode Stelem_I4 = new MsilOpCode(MsilCode.Stelem_I4, -798697819);
        public static readonly MsilOpCode Stelem_I8 = new MsilOpCode(MsilCode.Stelem_I8, -798693723);
        public static readonly MsilOpCode Stelem_R4 = new MsilOpCode(MsilCode.Stelem_R4, -798689627);
        public static readonly MsilOpCode Stelem_R8 = new MsilOpCode(MsilCode.Stelem_R8, -798685531);
        public static readonly MsilOpCode Stelem_Ref = new MsilOpCode(MsilCode.Stelem_Ref, -798681435);
        public static readonly MsilOpCode Ldelem = new MsilOpCode(MsilCode.Ldelem, -261699923);
        public static readonly MsilOpCode Stelem = new MsilOpCode(MsilCode.Stelem, 6669997);
        public static readonly MsilOpCode Unbox_Any = new MsilOpCode(MsilCode.Unbox_Any, 6727341);
        public static readonly MsilOpCode Conv_Ovf_I1 = new MsilOpCode(MsilCode.Conv_Ovf_I1, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U1 = new MsilOpCode(MsilCode.Conv_Ovf_U1, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I2 = new MsilOpCode(MsilCode.Conv_Ovf_I2, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U2 = new MsilOpCode(MsilCode.Conv_Ovf_U2, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I4 = new MsilOpCode(MsilCode.Conv_Ovf_I4, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U4 = new MsilOpCode(MsilCode.Conv_Ovf_U4, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I8 = new MsilOpCode(MsilCode.Conv_Ovf_I8, 7084709);
        public static readonly MsilOpCode Conv_Ovf_U8 = new MsilOpCode(MsilCode.Conv_Ovf_U8, 7084709);
        public static readonly MsilOpCode Refanyval = new MsilOpCode(MsilCode.Refanyval, 6953645);
        public static readonly MsilOpCode Ckfinite = new MsilOpCode(MsilCode.Ckfinite, 7346853);
        public static readonly MsilOpCode Mkrefany = new MsilOpCode(MsilCode.Mkrefany, 6699693);
        public static readonly MsilOpCode Ldtoken = new MsilOpCode(MsilCode.Ldtoken, 275385004);
        public static readonly MsilOpCode Conv_U2 = new MsilOpCode(MsilCode.Conv_U2, 6953637);
        public static readonly MsilOpCode Conv_U1 = new MsilOpCode(MsilCode.Conv_U1, 6953637);
        public static readonly MsilOpCode Conv_I = new MsilOpCode(MsilCode.Conv_I, 6953637);
        public static readonly MsilOpCode Conv_Ovf_I = new MsilOpCode(MsilCode.Conv_Ovf_I, 6953637);
        public static readonly MsilOpCode Conv_Ovf_U = new MsilOpCode(MsilCode.Conv_Ovf_U, 6953637);
        public static readonly MsilOpCode Add_Ovf = new MsilOpCode(MsilCode.Add_Ovf, -261739867);
        public static readonly MsilOpCode Add_Ovf_Un = new MsilOpCode(MsilCode.Add_Ovf_Un, -261739867);
        public static readonly MsilOpCode Mul_Ovf = new MsilOpCode(MsilCode.Mul_Ovf, -261739867);
        public static readonly MsilOpCode Mul_Ovf_Un = new MsilOpCode(MsilCode.Mul_Ovf_Un, -261739867);
        public static readonly MsilOpCode Sub_Ovf = new MsilOpCode(MsilCode.Sub_Ovf, -261739867);
        public static readonly MsilOpCode Sub_Ovf_Un = new MsilOpCode(MsilCode.Sub_Ovf_Un, -261739867);
        public static readonly MsilOpCode Endfinally = new MsilOpCode(MsilCode.Endfinally, 23333605);
        public static readonly MsilOpCode Leave = new MsilOpCode(MsilCode.Leave, 23333376);
        public static readonly MsilOpCode Leave_S = new MsilOpCode(MsilCode.Leave_S, 23333391);
        public static readonly MsilOpCode Stind_I = new MsilOpCode(MsilCode.Stind_I, -530294107);
        public static readonly MsilOpCode Conv_U = new MsilOpCode(MsilCode.Conv_U, 6953637);
        public static readonly MsilOpCode Prefix7 = new MsilOpCode(MsilCode.Prefix7, 6554757);
        public static readonly MsilOpCode Prefix6 = new MsilOpCode(MsilCode.Prefix6, 6554757);
        public static readonly MsilOpCode Prefix5 = new MsilOpCode(MsilCode.Prefix5, 6554757);
        public static readonly MsilOpCode Prefix4 = new MsilOpCode(MsilCode.Prefix4, 6554757);
        public static readonly MsilOpCode Prefix3 = new MsilOpCode(MsilCode.Prefix3, 6554757);
        public static readonly MsilOpCode Prefix2 = new MsilOpCode(MsilCode.Prefix2, 6554757);
        public static readonly MsilOpCode Prefix1 = new MsilOpCode(MsilCode.Prefix1, 6554757);
        public static readonly MsilOpCode Prefixref = new MsilOpCode(MsilCode.Prefixref, 6554757);
        public static readonly MsilOpCode Arglist = new MsilOpCode(MsilCode.Arglist, 279579301);
        public static readonly MsilOpCode Ceq = new MsilOpCode(MsilCode.Ceq, -257283419);
        public static readonly MsilOpCode Cgt = new MsilOpCode(MsilCode.Cgt, -257283419);
        public static readonly MsilOpCode Cgt_Un = new MsilOpCode(MsilCode.Cgt_Un, -257283419);
        public static readonly MsilOpCode Clt = new MsilOpCode(MsilCode.Clt, -257283419);
        public static readonly MsilOpCode Clt_Un = new MsilOpCode(MsilCode.Clt_Un, -257283419);
        public static readonly MsilOpCode Ldftn = new MsilOpCode(MsilCode.Ldftn, 279579300);
        public static readonly MsilOpCode Ldvirtftn = new MsilOpCode(MsilCode.Ldvirtftn, 11184804);
        public static readonly MsilOpCode Ldarg = new MsilOpCode(MsilCode.Ldarg, 279317171);
        public static readonly MsilOpCode Ldarga = new MsilOpCode(MsilCode.Ldarga, 279579315);
        public static readonly MsilOpCode Starg = new MsilOpCode(MsilCode.Starg, -257680717);
        public static readonly MsilOpCode Ldloc = new MsilOpCode(MsilCode.Ldloc, 279317166);
        public static readonly MsilOpCode Ldloca = new MsilOpCode(MsilCode.Ldloca, 279579310);
        public static readonly MsilOpCode Stloc = new MsilOpCode(MsilCode.Stloc, -257680722);
        public static readonly MsilOpCode Localloc = new MsilOpCode(MsilCode.Localloc, 11156133);
        public static readonly MsilOpCode Endfilter = new MsilOpCode(MsilCode.Endfilter, -240895259);
        public static readonly MsilOpCode Unaligned = new MsilOpCode(MsilCode.Unaligned, 10750096);
        public static readonly MsilOpCode Volatile = new MsilOpCode(MsilCode.Volatile, 10750085);
        public static readonly MsilOpCode Tail = new MsilOpCode(MsilCode.Tail, 10750085);
        public static readonly MsilOpCode Initobj = new MsilOpCode(MsilCode.Initobj, -257673555);
        public static readonly MsilOpCode Constrained = new MsilOpCode(MsilCode.Constrained, 10750093);
        public static readonly MsilOpCode Cpblk = new MsilOpCode(MsilCode.Cpblk, -794527067);
        public static readonly MsilOpCode Initblk = new MsilOpCode(MsilCode.Initblk, -794527067);
        public static readonly MsilOpCode Rethrow = new MsilOpCode(MsilCode.Rethrow, 27526917);
        public static readonly MsilOpCode Sizeof = new MsilOpCode(MsilCode.Sizeof, 279579309);
        public static readonly MsilOpCode Refanytype = new MsilOpCode(MsilCode.Refanytype, 11147941);
        public static readonly MsilOpCode Readonly = new MsilOpCode(MsilCode.Readonly, 10750085);

        // ReSharper restore InconsistentNaming
    }
}
